# Generated by Django 4.0.2 on 2022-02-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('link', models.URLField()),
                ('clicks', models.IntegerField()),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('clicks', models.IntegerField()),
                ('views', models.IntegerField()),
                ('ad', models.ManyToManyField(to='advertiser_management.Ad')),
            ],
        ),
    ]
