# Generated by Django 4.0.2 on 2022-02-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0002_remove_advertiser_ad_ad_advertiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
