# Generated by Django 4.0.2 on 2022-02-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0005_remove_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
