# Generated by Django 4.0.2 on 2022-02-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0006_alter_ad_clicks_alter_ad_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.IntegerField(default=5, primary_key=True, serialize=False),
        ),
    ]
