# Generated by Django 4.0.2 on 2022-02-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0008_alter_ad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
