# Generated by Django 4.0.2 on 2022-02-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0014_alter_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
