# Generated by Django 4.0.2 on 2022-02-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0015_alter_ad_image_alter_ad_link_alter_advertiser_clicks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='static_cdn/DEBR0551.JPG', upload_to='upload/'),
        ),
    ]
