# Generated by Django 4.0.2 on 2022-02-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0023_alter_click_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='views',
        ),
    ]
