# Generated by Django 4.0.2 on 2022-02-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0025_alter_click_time_alter_view_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='click',
            old_name='adId',
            new_name='ad',
        ),
        migrations.RenameField(
            model_name='view',
            old_name='adId',
            new_name='ad',
        ),
    ]
