# Generated by Django 3.2.12 on 2022-03-04 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0028_dailyreport_hourlyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('count_view', models.IntegerField(default=0)),
                ('count_click', models.IntegerField(default=0)),
                ('daily', models.BooleanField(default=False)),
                ('hourly', models.BooleanField(default=False)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.ad')),
            ],
        ),
        migrations.RemoveField(
            model_name='hourlyreport',
            name='ad',
        ),
        migrations.DeleteModel(
            name='DailyReport',
        ),
        migrations.DeleteModel(
            name='HourlyReport',
        ),
    ]
